export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_CURRENT_CUSTOMER = 'SET_CURRENT_CUSTOMER';
export const CUSTOMER_LOADING = 'CUSTOMER_LOADING';
export const GET_ERRORS = 'GET_ERRORS';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const REGISTER_CUSTOMER = 'REGISTER_CUSTOMER';

export const GET_ALL_ORDERS_OF_CUSTOMER_ID = 'GET_ALL_ORDERS_OF_CUSTOMER_ID';
export const ORDER_LOADING = 'ORDER_LOADING';
export const FETCH_ORDER_BY_ID = 'FETCH_ORDER_BY_ID';
export const FETCH_ALL_DISTINCT_CUSTOMERS = 'FETCH_ALL_DISTINCT_CUSTOMERS';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const ERROR_ORDER = 'ERROR_ORDER';